#!/bin/bash

GIT_DIR="/tmp/zfatlas/.git"
TEMPLATES="/tmp/www/inc/templates/"
ASSETS=( \
	javascript/vs.js \
	styles/zfatlas.css \
	styles/viewer.css \
)

create_substitution()
{
	# get short commit hash for last file modification
	commit=$(git log -n1 --pretty=%h -- $1)

	# return substitution for this asset?commit
	# (periods should really be escaped in the search pattern)
	# http://stackoverflow.com/questions/407523/escape-a-string-for-sed-search-pattern
	echo "-e 's|\"$1\(?[0-9a-f]\+\)\?|\"$1?$commit|'"
}

# main()
subs=()
for asset in "${ASSETS[@]}"; do
	# a bash array push:
	subs=( "${subs[@]}" $(create_substitution $asset) )
done

find "${TEMPLATES}" -type f \| xargs sed -i "${subs[@]}"

